servers:
  - id: JAVA_RUTGERS
    hostname: java
    hostaddress: java.cs.rutgers.edu
    crontab_name: java_crontab
  
  # - id: PERL_RUTGERS
  #   hostname: perl
  #   hostaddress: perl.cs.rutgers.edu
  #   crontab_name: perl_crontab