servers:
  - id: pkey_ec2
    hostname: ubuntu
    hostaddress: 3.84.98.13
    crontab_name: ec2_crontab
  
  - id: pkey_ec2
    hostname: ubuntu
    hostaddress: 3.84.98.13
    crontab_name: java_crontab