servers:
  - id: pkey_ec2
    hostname: ubuntu
    hostaddress: 54.164.3.28
    crontab_name: ec2_crontab
  
  - id: pkey_ec2
    hostname: ubuntu
    hostaddress: 54.164.3.28
    crontab_name: java_crontab