servers:
  - id: pkey_ec2
    hostname: ubuntu
    hostaddress: 44.202.31.193
    crontab_name: ec2_crontab
  
  - id: pkey_ec2
    hostname: ubuntu
    hostaddress: 44.202.31.193
    crontab_name: java_crontab