servers:
  - id: pkey_ec2
    hostname: ubuntu
    hostaddress: 18.206.119.97
    crontab_name: ec2_crontab
  
  - id: pkey_ec2
    hostname: ubuntu
    hostaddress: 18.206.119.97
    crontab_name: java_crontab